apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcore-deployment
spec:
  selector:
    matchLabels:
      app: aspnetcore-pod
  template:
    metadata:
      labels:
        app: aspnetcore-pod
    spec:
      containers:
      - name: aspnetcore-container
        image: aspnetapp:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        